# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e18253237f9d4d14c599bbe80bf45f92e593ef20bf4d7dca2b94f501bfcad05f201bf29d99951c2551a3a760385fab539ba111a48655c81ee080e53b6f518077

test:
  secret_key_base: e5a2453f8157d5aa735077acfd89b21b93e7fc48535b0cd7220bb63d368efb4d22c4f6e9f96bce67f8b794811863443bfe953ce01d80ac2867fec4fe6786a25f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
